name: Echo Issue Event

on:
  issues:
    types: 
      - opened
      - edited

jobs:
  echo:
    runs-on: ubuntu_latest
    steps:
      - name: echo event
        run: echo "${{ toJSON(github.event) }}"
